### PR TITLE
Helan/Playground

### PR DESCRIPTION
**Pull request by Helan23**
This is a source code based on reading a file and committing changes to the word into asterisks.

### CODE REVIEW

**Comment by Helan23** [comment]
U have closed it sir

**Comment by hsejar** [comment]
I tried calling you as planned and you didn't answer.
So I thought you were not interested.
Regards,
Rajesh Sukumaran

Co-Founder and CEO,
Finahub Technology Solutions <http://www.finahub.com/>

**Comment by Helan23** [comment]
I didn't get the call sir.

**Comment by hsejar** [comment]
Ok then let us have a call today afternoon.

Regards,

Rajesh Sukumaran

**Comment by Helan23** [comment]
Am in college right now sir. Can we place call on Saturday

**Comment by hsejar** [comment]
Sure, we can do that.

Regards,

Rajesh Sukumaran

**Pull request closed without merging**
