### PR TITLE
Create Sunny_2.pdf

### PR DESCRIPTION
**Pull request by SunnyBakhru**
I have added both angular and java side code ....

### CODE REVIEW

**Comment by SunnyBakhru** [comment]
i have added java and angular side code .
 Name Sunny Bakhru
mail id - sunny.bakhru@gmail.com

**Comment by hsejar** [comment]
Hi Sunny, thank you for your effort. We will review the code and get back to you

**Comment by ajithkg** [comment]
Hi Sunny,
  We are unable to find any code on the pull request.  Can you submit the pull request again?

**Comment by SunnyBakhru** [comment]
Hello Finahub/PlayGround,

I have pushed the code .Please go through it and let me if anything needs
to be changed.

Thanks
Sunny Bakhru

**Pull request closed without merging**
